# Generated by Django 5.0.6 on 2024-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predictor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictor",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="predictor",
            name="description",
        ),
        migrations.RemoveField(
            model_name="predictor",
            name="model",
        ),
        migrations.RemoveField(
            model_name="predictor",
            name="name",
        ),
        migrations.RemoveField(
            model_name="predictor",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="predictor",
            name="isSafe",
            field=models.BooleanField(default=False),
        ),
    ]
